(part "1663969"
    (packageRef "1663969")
    (interface
        (port "1" (symbPinId 1) (portName "MH1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "MH2") (portType INOUT))
        (port "P1" (symbPinId 3) (portName "P1") (portType INOUT))
        (port "P2" (symbPinId 4) (portName "P2") (portType INOUT))
        (port "P3" (symbPinId 5) (portName "P3") (portType INOUT))
        (port "P4" (symbPinId 6) (portName "P4") (portType INOUT))
        (port "P5" (symbPinId 7) (portName "P5") (portType INOUT))
        (port "P6" (symbPinId 8) (portName "P6") (portType INOUT))
        (port "P7" (symbPinId 9) (portName "P7") (portType INOUT))
        (port "P8" (symbPinId 10) (portName "P8") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Phoenix Contact")
    (property "Manufacturer_Part_Number" "1663969")
    (property "Description" "RJ45 PCB connector, number of positions: 8, 100 Mbps")
    (property "Datasheet_Link" "https://www.phoenixcontact.com/en-ae/products/rj45-pcb-connector-cuc-ib4m-j1st-at-r4t-p-1663969")
    (property "symbolName1" "1663969")
)
