(part "SRR1260-330M"
    (packageRef "SRR1260-150M")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "652-SRR1260-330M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/SRR1260-330M?qs=R2jSSvul3fC3V4%252BTrq0P0w%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "SRR1260-330M")
    (property "Description" "Power inductor SMD shielded 33uH Bourns SRR1260 Series Shielded Wire-wound SMD Inductor with a Ferrite Core, 33 uH +/-20% Wire-Wound 3A Idc Q:27")
    (property "Datasheet_Link" "https://www.bourns.com/docs/Product-Datasheets/SRR1260.pdf")
    (property "symbolName1" "SRR1260-330M")
)
