(part "3588"
    (packageRef "3588")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "534-3588")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Keystone-Electronics/3588?qs=%2F%252BPMR94VuMZoVX%252BPrVg9MA%3D%3D")
    (property "Manufacturer_Name" "Keystone Electronics")
    (property "Manufacturer_Part_Number" "3588")
    (property "Description" "Fuse Holder SMT MINI FUSE HOLDER .630 X .290")
    (property "Datasheet_Link" "https://www.keyelco.com/product-pdf.cfm?p=311")
    (property "symbolName1" "3588")
)
