(part "TXU0101DBVR"
    (packageRef "SOT95P280X145-6N")
    (interface
        (port "1" (symbPinId 1) (portName "VCCA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "A") (portType INOUT))
        (port "4" (symbPinId 4) (portName "BY") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OE") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VCCB") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TXU0101DBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TXU0101DBVR?qs=IPgv5n7u5QaPPuDmRaldJw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TXU0101DBVR")
    (property "Description" "Translation - Voltage Levels Single channel fixed-direction level shifter")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/txu0101.pdf?ts=1669130963626&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FTXU0101")
    (property "symbolName1" "TXU0101DBVR")
)
